### ISSUE TITLE
Set autoshutdown time to never

### ISSUE THREAD

**Issue by Tricked-dev** [MultiMote/niimbluelib#3]
Hi i noticed via the app you can set auto shutdown to never, i did some testing and did confirm that 45 min does not exist on my b1 model and that 45 min has been replaced with 1 hour and that 1 hour is never

![Screenshot_20241014-183310](https://github.com/user-attachments/assets/06f7378c-5f98-4f72-bd80-d9ef07f04a13)

correct enum should be

```ts

export enum AutoShutdownTime {
  Shutdown15min = 1,
  Shutdown30min = 2,
  Shutdown60min = 3,
  ShutdownNever = 4,
}
```

atleast for my printer

**Comment by MultiMote** [comment]
There is no "right" version. B1:

![Screenshot_2024-10-14-19-48-58-760_com gengcon android jccloudprinter](https://github.com/user-attachments/assets/d7901d2c-79b2-4690-9adf-bdd67a6e7dad)

D110:

![Screenshot_2024-10-14-19-48-32-659_com gengcon android jccloudprinter](https://github.com/user-attachments/assets/d3bd0059-1345-4382-81d2-0c2c35ff3056)

I will think about what I can do with this.

**Comment by Tricked-dev** [comment]
Maybe you could create 2 enum variants and accept both in the function?

**Comment by MultiMote** [comment]
Well, I've renamed the values to a generic format and added comments. I haven't found a way to figure out how to associate the auto shutdown values with the printer.

https://github.com/MultiMote/niimbluelib/blob/85143808491dd77ad76e0d397062db46815551cb/src/packets/index.ts#L126-L135
