### ISSUE TITLE
Allow newPrintTask to accept image as well instead of canvas

### ISSUE THREAD

**Issue by dotnetdreamer** [MultiMote/niimbluelib#6]
This will open the door to be used in https://nativescript.org/ and ionic capacitor/cordova

**Comment by MultiMote** [comment]
`newPrintTask` does not have canvas parameter.

**Comment by dotnetdreamer** [comment]
Sorry it was about ImageEncoder. Adding a default encoders will definitely help. The one used for nodejs headless mode doesn't work on web.

Also add option to download the image from sevelt [web app](https://github.com/MultiMote/niimblue) as well. This way people can host your web app in their server (instead of niimbot app) they can use it inside a custom made mobile app (via webview) and then download the image and send it to printer

**Comment by MultiMote** [comment]
> Sorry it was about ImageEncoder. Adding a default encoders will definitely help

What type of input should I add? Can you provide a link to the object reference?

> Also add option to download the image from sevelt [web app](https://github.com/MultiMote/niimblue) as well

What do you mean by "image"? There is already an export/import feature so you can transfer your templates between devices.

**Comment by dotnetdreamer** [comment]
The demo provides https://niim.mmote.ru/ only export/import json and not image. I would like to deploy this to my server (like your demo) and embedd the link in Mobile webview where I can download the image to my phone. And then my (another) app running inside same phone can use that image and directly print.

**Comment by dotnetdreamer** [comment]
You have 2 encoders i.e one for [canvas](https://github.com/MultiMote/niimblue/blob/b6780f7eabd1453121be5620b7148c3da1080cff/src/lib/PrintPreview.svelte#L92) and other for [nodejs](https://github.com/MultiMote/niimbluelib-headless/blob/c7b5d530efdb36ab0d152f929cc2eaede6dd9efb/src/cli.ts#L83)

**Comment by MultiMote** [comment]
I've not included png encoder to the niimbluelib because it browser-only. I wouldn't want to add unnecessary dependencies.

**Comment by MultiMote** [comment]
PNG export added

![image](https://github.com/user-attachments/assets/526ee9f3-f6ae-4e02-97ba-a4ccef509ab5)

**Comment by dotnetdreamer** [comment]
I tried. I set my side to 50x30 and download the png but the actual file size is 400x240.

![image](https://github.com/user-attachments/assets/4bb72380-275c-4e8f-b879-315e8e8bd631)

**Comment by dotnetdreamer** [comment]
And why do we have to encode image ? what does encoded image means ?

**Comment by MultiMote** [comment]
> I tried. I set my side to 50x30 and download the png but the actual file size is 400x240.

50x30 is a size in millimeters. It's a human-friendly unit. Actual unit is pixels.

![image](https://github.com/user-attachments/assets/54613c68-ca20-4781-85cf-b9000b426e35)

> And why do we have to encode image ? what does encoded image means ?

NIIMBOT printer accepts black and white pixel bits grouped in bytes. E.g. `0xFF 0xFF` holds 16 black pixels.
ImageEncoder converts image (any color except white converted to black) to black/white pixel rows, counts repeats for duplicating rows and counts empty (white) rows.
