### ISSUE TITLE
D110 printer works only with B1 device type.

### ISSUE THREAD

**Issue by berhalak** [MultiMote/niimbluelib#7]
D110 printer works only with B1 device type.

I think even the library itself detects this printer as B1 type.

**Comment by MultiMote** [comment]
Please post printer info from [niimblue](https://niim.mmote.ru) (Gear icon near printer name). Maybe you have D110_M (300 dpi version of D110). It uses same print task format as B1.

Here is print task dictionary: https://github.com/MultiMote/niimbluelib/blob/8e15d2e7bfd4bac24e8c97036566d0443fde1b41/src/print_tasks/index.ts#L46-L51

**Comment by berhalak** [comment]
Yes, you are right.

```
Printer info:
connectResult: 3
protocolVersion: 4
modelId: 2320
serial: G621120613
mac: 12:06:13:fc:10:02
charge: 4
autoShutdownTime: 3
labelType: 1
hardwareVersion: 0x0401
softwareVersion: 0x040a
Model metadata:
model: D110_M
id: 2320
dpi: 203
printDirection: left
printheadPixels: 120
paperTypes: 1,5
densityMin: 1
densityMax: 5
densityDefault: 3
Heartbeat data:
paperState: -1
rfidReadState: -1
lidClosed: false
powerLevel: 4
```

**Comment by MultiMote** [comment]
So it's expected behavior. A task name does not necessarily mean a certain model. This is just the first model I came across for particular protocol.
